AppDjango/AppDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manejador_cronogramas/', include('manejador_cronogramas.urls')),
    path('manejador_facturacion/', include('manejador_facturacion.urls')),
    path('manejador_batch_processing/', include('manejador_batch_processing.urls')),
    path('manejador_reportes/', include('manejador_reportes.urls')),
    path('manejador_logs/', include('manejador_logs.urls')),
    path('', RedirectView.as_view(url='/admin/', permanent=False)),
    path('health-check/', views.healthCheck),
    path(r'', include('django.contrib.auth.urls')),
    path(r'', include('social_django.urls')),
]

AppDjango/manejador_facturacion/urls.py
from django.urls import path
from .views import listar_facturas, listado_pagos_estudiante, pagar

app_name = 'manejador_facturacion'  # Esto es necesario para el namespace
urlpatterns = [
    path('', listar_facturas, name='listar_facturas'),
    path('conceptos_pago/<int:estudiante_id>/', listado_pagos_estudiante, name='listado_conceptos_pago'),
    path('pagar/', pagar, name='pagar'),
]

AppDjango/manejador_reportes/urls.py
from django.urls import path
from .views import generar_reporte, home, generar_cartera

app_name = 'manejador_reportes'  # Esto es necesario para el namespace
urlpatterns = [
    path('', generar_reporte, name='generar_reporte'),
    path('', home, name='home'),  
    path('reporte/<str:nombre_institucion>/<str:mes>/', generar_reporte, name='generar_reporte'),
    path('cartera_general/<str:nombre_institucion>/<str:mes>/', generar_cartera, name='generar_cartera'),
]

AppDjango/manejador_reportes/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .services import obtener_cuentas_por_cobrar, obtener_cartera_general
import redis
import json
from django.contrib.auth.decorators import login_required
from AppDjango.auth0backend import getRole, getNickname
import requests


# Función para verificar el nickname e institución en la API
def verificar_institucion(nickname, nombre_institucion):
    url = f"http://10.128.0.7:8080/instituciones/institution/{nickname}/"
    try:
        response = requests.get(url)
        data = response.json()
        
        # Si devuelve error, la verificación falla
        if 'error' in data:
            return False
        
        # Verifica si la institución recibida coincide con la proporcionada
        print("Se obtienen los datos de la API:", data, "con la URL de la API:", url)
        return data.get("institution") == nombre_institucion
    except requests.RequestException as e:
        print(f"Error al verificar la institución: {e}")
        return False
    # credenciales_validas = {
    #     'aux-jose-1': 'Western_Peaks_Elementary',
    #     'aux-camila-1': 'Ravenna_High_School'
    # }
    
    # return credenciales_validas.get(nickname) == nombre_institucion

@login_required
def generar_reporte(request, nombre_institucion, mes):
    role = getRole(request)
    nickname = getNickname(request)
    if role == 'Auxiliar contable':
        if verificar_institucion(nickname, nombre_institucion):
            key = f"cuentas_por_cobrar:{nombre_institucion}:{mes}"
            print(f"Key: {key}")

            r = redis.StrictRedis(host='10.128.0.5', port=6379, db=0)
            cuentas_por_cobrar = r.get(key)

            if cuentas_por_cobrar is not None:
                cuentas_por_cobrar = json.loads(cuentas_por_cobrar.decode('utf-8'))
                print("Hit Redis")
            else:
                print("No se encontraron datos en Redis, ejecutando la función...")
                nombre_institucion_con_espacios = nombre_institucion.replace('_', ' ')
                mes_con_espacios = mes.replace('_', ' ')
                
                try:
                    cuentas_por_cobrar = obtener_cuentas_por_cobrar(nombre_institucion_con_espacios, mes_con_espacios)
                    print("Datos obtenidos de la función:", cuentas_por_cobrar)
                    r.set(key, json.dumps(cuentas_por_cobrar), ex=60 * 60 * 24)
                except Exception as e:
                    print(f"Error al obtener cuentas por cobrar: {e}")
                    cuentas_por_cobrar = []

            return render(request, 'listar.html', {'cuentas_por_cobrar': cuentas_por_cobrar})
        else:
            return JsonResponse({"message": "La institución a la cual quieres acceder no es a la que perteneces"})
    else:
        return JsonResponse({"message": "Unauthorized User"})

@login_required
def generar_cartera(request, nombre_institucion, mes):
    role = getRole(request)
    nickname = getNickname(request)
    if role == 'Auxiliar contable':
        if verificar_institucion(nickname, nombre_institucion):
            key = f"cartera_general:{nombre_institucion}:{mes}"
            print(f"Key: {key}")

            r = redis.StrictRedis(host='10.128.0.5', port=6379, db=0)
            cartera_general = r.get(key)

            if cartera_general is not None:
                cartera_general = json.loads(cartera_general.decode('utf-8'))
                print("Hit Redis")
            else:
                print("No se encontraron datos en Redis, ejecutando la función...")
                nombre_institucion_con_espacios = nombre_institucion.replace('_', ' ')
                mes_con_espacios = mes.replace('_', ' ')

                try:
                    cartera_general = obtener_cartera_general(nombre_institucion_con_espacios, mes_con_espacios)
                    print("Datos obtenidos de la función:", cartera_general)
                    r.set(key, json.dumps(cartera_general), ex=60 * 60 * 24)
                except Exception as e:
                    print(f"Error al obtener cartera general: {e}")
                    cartera_general = []
            return render(request, 'cuentas.html', {'cartera_general': cartera_general})
        else:
            return JsonResponse({"message": "La institución a la cual quieres acceder no es a la que perteneces"})
    else:
        return JsonResponse({"message": "Unauthorized User"})

def home(request):
    return JsonResponse({"message": "Bienvenido a la aplicación"})

AppDjango/manejador_reportes/templates/cuentas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Valor Cuentas por Cobrar</title>
    <style>
        .rojo {
            color: red;
        }
        .verde {
            color: green;
        }
    </style>
</head>
<body>
    <h1>Valor de Cuentas por Cobrar</h1>

    <table border="1">
        <thead>
            <tr>
                <th>Institución</th>
                <th>Mes</th>
                <th>Valor deuda</th>
            </tr>
        </thead>
        <tbody>
            {% if cartera_general %}
                {% for cartera in cartera_general %}
                    <tr>
                        <td>{{ cartera.institucion }}</td> 
                        <td>{{ cartera.mes }}</td> <!-- mes -->
                        <td class="{% if cartera.total_deuda > 1000000 %}rojo{% else %}verde{% endif %}">
                            {{ cartera.total_deuda }}
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="8">No se encontraron resultados.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</body>
</html>

AppDjango/manejador_reportes/templates/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte de Cuentas por Cobrar</title>
</head>
<body>
<h1>Reporte de Cuentas por Cobrar</h1>

<table border="1">
    <thead>
    <tr>
        <th>Monto Recibo</th>
        <th>Mes</th>
        <th>Valor Detalle</th>
        <th>Estudiante</th>
        <th>Grado</th>
        <th>Institución</th>
        <th>Concepto</th>
        <th>Código</th>
        <th>Listado de pagos</th>
    </tr>
    </thead>
    <tbody>
    {% if cuentas_por_cobrar %}
        {% for cuenta in cuentas_por_cobrar %}
            <tr>
                <td>{{ cuenta.monto_recibo }}</td> <!-- monto_recibo -->
                <td>{{ cuenta.mes }}</td> <!-- mes -->
                <td>{{ cuenta.valor_detalle }}</td> <!-- valor_detalle -->
                <td>{{ cuenta.estudiante_id }} - {{ cuenta.nombre_estudiante }}</td>
                <!-- estudiante_id y nombre_estudiante -->
                <td>{{ cuenta.nombre_grado }}</td> <!-- nombre_grado -->
                <td>{{ cuenta.nombre_institucion }}</td> <!-- nombre_institucion -->
                <td>{{ cuenta.nombre_concepto }}</td> <!-- nombre_concepto -->
                <td>{{ cuenta.codigo }}</td> <!-- código -->
                <td>
                    <!-- Botón para redirigir al listado de pagos del estudiante -->
                    <a href="{% url 'manejador_facturacion:listado_conceptos_pago' cuenta.estudiante_id %}">
                        <button>Ver listado de pagos</button>
                    </a>
                </td> <!-- Acción con el botón -->
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="8">No se encontraron resultados.</td>
        </tr>
    {% endif %}
    </tbody>
</table>
</body>
</html>